name: Generate Seller Info CSV

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    environment: AUTH_DETAILS
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          
      - name: Install dependencies
        run: |
          pip install selenium webdriver-manager requests selenium-requests

      - name: Download ChromeDriver
        run: |
          python -m webdriver_manager.chrome install   

      - name: Run Cookies for login
        run: | 
          python cookies.py
      - name: Scraping Script
        run: |
          python Jijiscraping.py 
        # Access cookies from the environment variable
        env :
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          COOKIES: ${{ secrets.SESSION_COOKIES }}
